### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jOb_6w/eth-account/

### ISSUE THREAD

**Issue by subhasisbanik** [ethereum/simplecasper#10]
While running,
pip install -r requirements.txt
Got,
"Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jOb_6w/eth-account/"

**Comment by ChihChengLiang** [comment]
Sorry, this repo is deprecated. Please check the current repo https://github.com/ethereum/casper
