### ISSUE TITLE
PoS: 環保又安全的區塊鏈共識機制 網頁的youtube連結放錯了....

### ISSUE THREAD

**Issue by AYEE0525** [ethereum/simplecasper#9]
因為官網沒地方讓我留言，只好留在這了
https://tw.pycon.org/2017/en-us/events/talk/347798441977446527/
裡面的youtube連結放錯放成這個: https://www.youtube.com/watch?v=uFBu2P1mwFU
但實際應該是這個: https://www.youtube.com/watch?v=jxLOZGGjqm4

**Comment by ChihChengLiang** [comment]
hihi @Chao-wei-chu  , sorry the talk is hosted by pycontw 2017 and this is the repo of Ethereum organization. Let me forward this issue to the pycontw team. Thanks.
